export { Portada } from './Portada'
export { Dolencia1 } from './Dolencia1'
export { Dolencia2 } from './Dolencia2'
export { Actividades1 } from './Actividades1'
export { VideoPanel } from './Video'
export { Evolucion1 } from './Evolucion1'
export { Evolucion2 } from './Evolucion2'
export { Evolucion3 } from './Evolucion3'
// export { Resumen } from './Resumen'
// export { Problema } from './Problema'
// export { Solucion } from './Solucion'
// export { Arquitectura } from './Arquitectura'
// export { Mercado } from './Mercado'
// export { Competencia } from './Competencia'
// export { Negocio } from './Negocio'
// export { Traccion } from './Traccion'
// export { Roadmap } from './Roadmap'
// export { Riesgos } from './Riesgos'
// export { Equipo } from './Equipo'
export { CTA } from './CTA'
// export { ResumenProblema } from './ResumenProblema'