export { SeccionPlataformas } from './SeccionPlataformas'
export { PortadaPlataformas } from './PortadaPlataformas'
export { DetallePlataforma } from './DetallePlataforma'
export { InstagramFacebook } from './InstagramFacebook'
export { ORDEN, CONTENIDO, type PlataformaKey } from './data'
