import { SlideMetadata } from '@src/context/SlidesContext'
import {
	EstrategiaPortada,
	QuienEsSolware,
	PropuestaValor,
	AnalisisMacro,
	MicroentornoMonartechAvila,
	VentajasOportunidades,
	VentajasOportunidadesDos,
	MicroentornoInboundInfoLab,
	ObjetivosComerciales,
	ObjetivosDigitales,
	BuyerPersonas,
	PlataformasBuyerPersona,
	ObservacionesSeo,
	PilaresContenido,
	SeccionPlataformas,
	PublicidadDigital,
	PlanAccion,
	AgradecimientoFinal,
} from '@src/slides/index'

export const slidesConfig: SlideMetadata[] = [
	{
		id: 'portada',
		titulo: 'Estrategia Digital',
		grupo: 'Introducción',
		icono: 'Presentation',
		component: EstrategiaPortada,
	},
	{
		id: 'quien-es-solware',
		titulo: '¿Quién es Solware Agency?',
		grupo: 'Introducción',
		icono: 'Building2',
		component: QuienEsSolware,
	},
	{
		id: 'propuesta-valor',
		titulo: 'Propuesta de Valor',
		grupo: 'Introducción',
		icono: 'Sparkles',
		component: PropuestaValor,
	},
	{
		id: 'analisis-macro',
		titulo: 'Análisis Macroentorno',
		grupo: 'Análisis',
		icono: 'Globe',
		component: AnalisisMacro,
	},
	{
		id: 'microentorno-monartech-avila',
		titulo: 'Microentorno: Monartech Ávila',
		grupo: 'Análisis',
		icono: 'Building',
		component: MicroentornoMonartechAvila,
	},
	{
		id: 'ventajas-oportunidades',
		titulo: 'Ventajas y Oportunidades',
		grupo: 'Análisis',
		icono: 'TrendingUp',
		component: VentajasOportunidades,
	},
	{
		id: 'microentorno-inbound-infolab',
		titulo: 'Microentorno: Inbound InfoLab',
		grupo: 'Análisis',
		icono: 'Building',
		component: MicroentornoInboundInfoLab,
	},
	{
		id: 'ventajas-oportunidades-dos',
		titulo: 'Ventajas y Oportunidades (2)',
		grupo: 'Análisis',
		icono: 'TrendingUp',
		component: VentajasOportunidadesDos,
	},
	{
		id: 'objetivos-comerciales',
		titulo: 'Objetivos Comerciales',
		grupo: 'Estrategia',
		icono: 'Target',
		component: ObjetivosComerciales,
	},
	{
		id: 'objetivos-digitales',
		titulo: 'Objetivos Digitales',
		grupo: 'Estrategia',
		icono: 'Laptop',
		component: ObjetivosDigitales,
	},
	{
		id: 'buyer-personas',
		titulo: 'Buyer Personas',
		grupo: 'Estrategia',
		icono: 'Users',
		component: BuyerPersonas,
	},
	{
		id: 'plataformas-buyer-persona',
		titulo: 'Plataformas por Buyer Persona',
		grupo: 'Estrategia',
		icono: 'Network',
		component: PlataformasBuyerPersona,
	},
	{
		id: 'observaciones-seo',
		titulo: 'Observaciones SEO',
		grupo: 'Táctica',
		icono: 'Search',
		component: ObservacionesSeo,
	},
	{
		id: 'pilares-contenido',
		titulo: 'Pilares de Contenido',
		grupo: 'Táctica',
		icono: 'FileText',
		component: PilaresContenido,
	},
	{
		id: 'plataformas-digitales',
		titulo: 'Plataformas Digitales',
		grupo: 'Táctica',
		icono: 'Share2',
		component: SeccionPlataformas,
	},
	{
		id: 'publicidad-digital',
		titulo: 'Publicidad Digital',
		grupo: 'Táctica',
		icono: 'Megaphone',
		component: PublicidadDigital,
	},
	{
		id: 'plan-accion',
		titulo: 'Plan de Acción',
		grupo: 'Implementación',
		icono: 'CalendarCheck',
		component: PlanAccion,
	},
	{
		id: 'agradecimiento',
		titulo: 'Gracias',
		grupo: 'Cierre',
		icono: 'Heart',
		component: AgradecimientoFinal,
	},
]
